export class Resources {

    public static MtgImageUrls = [
        { name: "IMAGEURL_BORDER_W", path: "assets/img/mtg/borders/w.png" },
        { name: "IMAGEURL_BORDER_W_CREATURE", path: "assets/img/mtg/borders/w_creature.png" },
        { name: "IMAGEURL_BORDER_U", path: "assets/img/mtg/borders/u.png" },
        { name: "IMAGEURL_BORDER_U_CREATURE", path: "assets/img/mtg/borders/u_creature.png" },
        { name: "IMAGEURL_BORDER_B", path: "assets/img/mtg/borders/b.png" },
        { name: "IMAGEURL_BORDER_B_CREATURE", path: "assets/img/mtg/borders/b_creature.png" },
        { name: "IMAGEURL_BORDER_R", path: "assets/img/mtg/borders/r.png" },
        { name: "IMAGEURL_BORDER_R_CREATURE", path: "assets/img/mtg/borders/r_creature.png" },
        { name: "IMAGEURL_BORDER_G", path: "assets/img/mtg/borders/g.png" },
        { name: "IMAGEURL_BORDER_G_CREATURE", path: "assets/img/mtg/borders/g_creature.png" },
        { name: "IMAGEURL_BORDER_WU", path: "assets/img/mtg/borders/wu.png" },
        { name: "IMAGEURL_BORDER_WU_CREATURE", path: "assets/img/mtg/borders/wu_creature.png" },
        { name: "IMAGEURL_BORDER_WB", path: "assets/img/mtg/borders/wb.png" },
        { name: "IMAGEURL_BORDER_WB_CREATURE", path: "assets/img/mtg/borders/wb_creature.png" },
        { name: "IMAGEURL_BORDER_RW", path: "assets/img/mtg/borders/rw.png" },
        { name: "IMAGEURL_BORDER_RW_CREATURE", path: "assets/img/mtg/borders/rw_creature.png" },
        { name: "IMAGEURL_BORDER_GW", path: "assets/img/mtg/borders/gw.png" },
        { name: "IMAGEURL_BORDER_GW_CREATURE", path: "assets/img/mtg/borders/gw_creature.png" },
        { name: "IMAGEURL_BORDER_UB", path: "assets/img/mtg/borders/ub.png" },
        { name: "IMAGEURL_BORDER_UB_CREATURE", path: "assets/img/mtg/borders/ub_creature.png" },
        { name: "IMAGEURL_BORDER_UR", path: "assets/img/mtg/borders/ur.png" },
        { name: "IMAGEURL_BORDER_UR_CREATURE", path: "assets/img/mtg/borders/ur_creature.png" },
        { name: "IMAGEURL_BORDER_GU", path: "assets/img/mtg/borders/gu.png" },
        { name: "IMAGEURL_BORDER_GU_CREATURE", path: "assets/img/mtg/borders/gu_creature.png" },
        { name: "IMAGEURL_BORDER_BR", path: "assets/img/mtg/borders/br.png" },
        { name: "IMAGEURL_BORDER_BR_CREATURE", path: "assets/img/mtg/borders/br_creature.png" },
        { name: "IMAGEURL_BORDER_BG", path: "assets/img/mtg/borders/bg.png" },
        { name: "IMAGEURL_BORDER_BG_CREATURE", path: "assets/img/mtg/borders/bg_creature.png" },
        { name: "IMAGEURL_BORDER_RG", path: "assets/img/mtg/borders/rg.png" },
        { name: "IMAGEURL_BORDER_RG_CREATURE", path: "assets/img/mtg/borders/rg_creature.png" },
        { name: "IMAGEURL_BORDER_M", path: "assets/img/mtg/borders/m.png" },
        { name: "IMAGEURL_BORDER_M_CREATURE", path: "assets/img/mtg/borders/m_creature.png" },
        { name: "IMAGEURL_BORDER_C", path: "assets/img/mtg/borders/c.png" },
        { name: "IMAGEURL_BORDER_C_CREATURE", path: "assets/img/mtg/borders/c_creature.png" },
    ]
}