name: "Subworkflow - Deployment"

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  deploy_ftp:
    name: Deploy via SSH
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Prepare Frontend build
        uses: actions/setup-node@v6
        with:
          node-version: 20.11.0

      - name: Build Frontend
        run: |
          npm ci
          npm run build

      - name: Copy via SSH
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist
          remote: drunken-discord-bot
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          privateKey: ${{ secrets.SSH_PRIVATEKEY }}